package com.ffusion.ffs.bpw.util.swift;

public abstract interface SWIFTConsts
{
  public static final String SWIFT_MESSAGE_TYPE_MT101 = "MT101";
  public static final String SWIFT_MESSAGE_TYPE_MT103 = "MT103";
  public static final String SWIFT_CONFIG_FILE_NAME_BPW = "bpwconfig.xml";
  public static final String SWIFT_CONFIG_FILE_NAME_APP = "swiftconfig.xml";
  public static final String ACTION_ADD = "add";
  public static final String EXCHANGE_RATE = "EXCHANGE_RATE";
  public static final String ORDERING_INSTITUTION_NAME = "ORDERING_INSTITUTION_NAME";
  public static final String ORDERING_INSTITUTION_ADDRESS = "ORDERING_INSTITUTION_ADDRESS";
  public static final String ORDERING_INSTITUTION_BIC = "ORDERING_INSTITUTION_BIC";
  public static final String ORDERING_CUSTOMER = "ORDERING_CUSTOMER";
  public static final String ORDERING_CUSTOMER_MEMBER_NAME = "ORDERING_CUSTOMER_MEMBER_NAME";
  public static final String ORDERING_INSTITUTION_MEMBER_NAME = "ORDERING_INSTITUTION_MEMBER_NAME";
  public static final String SENDERS_REFERENCE = "SENDERS_REFERENCE";
  public static final String SENDING_PARTY_ID = "SENDING_PARTY_ID";
  public static final String SEND_INSTITUTION_NAME = "SEND_INSTITUTION_NAME";
  public static final String SEND_INSTITUTION_BICCODE = "SEND_INSTITUTION_BICCODE";
  public static final String SENDER_CORRESPONDENT_NAME = "SENDER_CORRESPONDENT_NAME";
  public static final String SENDER_CORRESPONDENT_ADDRESS = "SENDER_CORRESPONDENT_ADDRESS";
  public static final String SENDER_CORRESPONDENT_PARTY_ID = "SENDER_CORRESPONDENT_PARTY_ID";
  public static final String SENDER_CORRESPONDENT_LOCATION = "SENDER_CORRESPONDENT_LOCATION";
  public static final String SENDER_CORRESPONDENT_BIC = "SENDER_CORRESPONDENT_BIC";
  public static final String SENDERS_CHARGES = "SENDERS_CHARGES";
  public static final String PAYMENT_ORIG_AMOUNT = "PAYMENT_ORIG_AMOUNT";
  public static final String PAYMENT_ORIG_CURRENCY = "PAYMENT_ORIG_CURRENCY";
  public static final String INTERMEDIARY_NAME = "INTERMEDIARY_NAME";
  public static final String INTERMEDIARY_ADDRESS = "INTERMEDIARY_ADDRESS";
  public static final String INTERMEDIARY_BIC = "INTERMEDIARY_BIC";
  public static final String INTERMEDIARY_PARTY_ID = "INTERMEDIARY_PARTY_ID";
  public static final String INTERMEDIARY_MEMBER_NAME = "INTERMEDIARY_MEMBER_NAME";
  public static final String RECEIVER_CORRESPONDENT_NAME = "RECEIVER_CORRESPONDENT_NAME";
  public static final String RECEIVER_CORRESPONDENT_ADDRESS = "RECEIVER_CORRESPONDENT_ADDRESS";
  public static final String RECEIVER_CORRESPONDENT_BIC = "RECEIVER_CORRESPONDENT_BIC";
  public static final String RECEIVER_CORRESPONDENT_PARTY_ID = "RECEIVER_CORRESPONDENT_PARTY_ID";
  public static final String RECEIVER_CORRESPONDENT_LOCATION = "RECEIVER_CORRESPONDENT_LOCATION";
  public static final String RECEIVERS_CHARGES = "RECEIVERS_CHARGES";
  public static final String SENDER_TO_RECEIVER_INFO = "SENDER_TO_RECEIVER_INFO";
  public static final String SENDER_TO_RECEIVER_MEMBER_NAME = "SENDER_TO_RECEIVER_MEMBER_NAME";
  public static final String SENDER_TO_RECEIVER_CODE = "SENDER_TO_RECEIVER_CODE";
  public static final String SENDER_TO_RECEIVER_ADDITIONAL_INFO = "SENDER_TO_RECEIVER_ADDITIONAL_INFO";
  public static final String SENDER_TO_RECEIVER_ADDITIONAL_LINES = "SENDER_TO_RECEIVER_ADDITIONAL_LINES";
  public static final String ACCOUNT_WITH_INSTITUTION_PARTY_ID = "ACCOUNT_WITH_INSTITUTION_PARTY_ID";
  public static final String ACCOUNT_WITH_INSTITUTION_MEMBER_NAME = "ACCOUNT_WITH_INSTITUTION_MEMBER_NAME";
  public static final String ACCOUNT_WITH_INSTITUTION_BIC = "ACCOUNT_WITH_INSTITUTION_BIC";
  public static final String ACCOUNT_WITH_INSTITUTION_NAME = "ACCOUNT_WITH_INSTITUTION_NAME";
  public static final String ACCOUNT_WITH_INSTITUTION_ADDRESS = "ACCOUNT_WITH_INSTITUTION_ADDRESS";
  public static final String ACCOUNT_WITH_INSTITUTION_LOCATION = "ACCOUNT_WITH_INSTITUTION_LOCATION";
  public static final String BENEFICIARY_NAME = "BENEFICIARY_NAME";
  public static final String BENEFICIARY_MEMBER_NAME = "BENEFICIARY_MEMBER_NAME";
  public static final String BENEFICIARY_BIC = "BENEFICIARY_BIC";
  public static final String BENEFICIARY_ADDRESS = "BENEFICIARY_ADDRESS";
  public static final String TIME_INDICATION = "TIME_INDICATION";
  public static final String BANK_OPERATION_CODE = "BANK_OPERATION_CODE";
  public static final String OPERATION_CODE = "OPERATION_CODE";
  public static final String TRANSACTION_TYPE_CODE = "TRANSACTION_TYPE_CODE";
  public static final String PARTY_IDENTIFIER_52 = "PARTY_IDENTIFIER_52";
  public static final String PARTY_IDENTIFIER_56 = "PARTY_IDENTIFIER_56";
  public static final String PARTY_IDENTIFIER_57 = "PARTY_IDENTIFIER_57";
  public static final String REMITTANCE_INFORMATION = "REMITTANCE_INFORMATION";
  public static final String DETAILS_OF_CHARGES = "DETAILS_OF_CHARGES";
  public static final String PAY_INSTRUCT = "PAY_INSTRUCT";
  public static final String ENVELOPE_CONTENTS = "ENVELOPE_CONTENTS";
  public static final String THIRD_REIMBURSEMENT_INSTI_ADDRESS = "THIRD_REIMBURSEMENT_INSTI_ADDRESS";
  public static final String THIRD_REIMBURSEMENT_INSTI_NAME = "THIRD_REIMBURSEMENT_INSTI_NAME";
  public static final String THIRD_REIMBURSEMENT_INSTI_PARTY_ID = "THIRD_REIMBURSEMENT_INSTI_PARTY_ID";
  public static final String THIRD_REIMBURSEMENT_INSTI_LOCATION = "THIRD_REIMBURSEMENT_INSTI_LOCATION";
  public static final String THIRD_REIMBURSEMENT_INSTI_BIC = "THIRD_REIMBURSEMENT_INSTI_BIC";
}


/* Location:           D:\drops\jd\jars\bpwcore.jar
 * Qualified Name:     com.ffusion.ffs.bpw.util.swift.SWIFTConsts
 * JD-Core Version:    0.7.0.1
 */