package com.ffusion.tasks.user;

import com.ffusion.tasks.Task;

public abstract interface UserTask
  extends Task
{
  public static final String USER = "User";
  public static final String USERS = "Users";
  public static final String USERS_COUNT = "UsersCount";
  public static final String OLD_USER = "OldUser";
  public static final String OLD_BUSINESS_EMPLOYEE = "OldBusinessEmployee";
  public static final String USER_SERVICE = "UserService";
  public static final String ENROLL_SERVICE = "EnrollService";
  public static final String CUSTOM_TAG_SERVICE = "CustomTagService";
  public static final String CUSTOM_TAG_VALUES_LIST = "CustomTagValuesList";
  public static final String USER_HISTORIES = "UserHistories";
  public static final String EXTRA_FIELDS = "ExtraFields";
  public static final String BANK_ID = "BankId";
  public static final String BUSINESS_ID = "BusinessId";
  public static final String PRIMARY_USER = "PrimaryUser";
  public static final String PRIMARY_BUSINESS_EMPLOYEE = "PrimaryBusinessEmployee";
  public static final String SECONDARY_BUSINESS_EMPLOYEE = "SecondaryBusinessEmployee";
  public static final String SEARCH_BUSINESS_EMPLOYEE = "SearchBusinessEmployee";
  public static final String SEARCH_CONSUMER = "SearchConsumer";
  public static final String CONSUMERS = "Consumers";
  public static final String CONSUMERS_COUNT = "ConsumersCount";
  public static final String PROFILE_ID = "ProfileId";
  public static final String USER_MARKET_SEGMENT = "UserMarketSegment";
  public static final String USER_SERVICES_PACKAGE = "UserServicesPackage";
  public static final String USERS_SEARCH_LIST_BY_SERVICES_PACKAGE = "UsersSearchListByServicesPackage";
  public static final String USERS_SEARCH_LIST_BY_MARKET_SEGMENT = "UsersSearchListByMarketSegment";
  public static final String USERS_SEARCH_LIST_BY_PERSONAL_BANKER = "UsersSearchListByPersonalBanker";
  public static final String TEMP_ASSIGNED_PB_USERS = "TempAssignedPbUsers";
  public static final String GROUP_SUMMARIES = "GroupSummaries";
  public static final String USER_BANK_IDS_LIST_BY_SERVICES_PACKAGE = "UserBankIdsListByServicesPackage";
  public static final String BANK_EMPLOYEE = "BankEmployee";
  public static final String HISTORY_ADD = "Add";
  public static final String HISTORY_MODIFY = "Modify";
  public static final String HISTORY_COMMENT = "Comment";
  public static final String USER_PROFILE_PROPERTIES = "UserProfileProperties";
  public static final String ENTITLEMENT_ADD_USER = "AddUser";
  public static final String ENTITLEMENT_ADD_USER_HISTORY = "AddUserHistory";
  public static final String ENTITLEMENT_EDIT_USER = "EditUser";
  public static final String ENTITLEMENT_DELETE_USER = "DeleteUser";
  public static final String ENTITLEMENT_GET_USERS = "GetUsers";
  public static final String ENTITLEMENT_GET_EXT_ACCOUNTINFO = "GetExtAccountInfo";
  public static final String ENTITLEMENT_GET_USER_CUSTOMTAGS = "GetUserCustomTags";
  public static final String ENTITLEMENT_GET_USER_EXTRAFIELDS = "GetUserExtraFields";
  public static final String ENTITLEMENT_MODIFY_ACCOUNT = "ModifyAccount";
  public static final String ENTITLEMENT_MODIFY_ACCOUNTS = "ModifyAccounts";
  public static final String ENTITLEMENT_MODIFY_USER_CUSTOMTAGS = "ModifyUserCustomTags";
  public static final String ENTITLEMENT_UPDATE_AVAILABLE_CUSTOMTAGS = "UpdateAvailableCustomTags";
  public static final String ENTITLEMENT_UPDATE_USER_CUSTOMTAGS = "UpdateUserCustomTags";
  public static final int TASK_ERROR_USER_SERVICE_NOT_FOUND_IN_SESSION = 3500;
  public static final int TASK_ERROR_ACCOUNTS_NOT_FOUND_IN_SESSION = 3501;
  public static final int TASK_ERROR_OLD_USER_NOT_FOUND_IN_SESSION = 3502;
  public static final int TASK_ERROR_USER_HISTORIES_NOT_FOUND_IN_SESSION = 3505;
  public static final int TASK_ERROR_NO_CUSTOM_TAGS_AVAILABLE = 3506;
  public static final int TASK_ERROR_BANK_EMPLOYEE_NOT_FOUND_IN_SESSION = 3507;
  public static final int TASK_ERROR_USER_PROFILE_PROPERTIES_NOT_FOUND_IN_SESSION = 3508;
  public static final int TASK_ERROR_INVALID_OLD_USERNAME = 3509;
  public static final int TASK_ERROR_INVALID_NEW_USERNAME = 3510;
  public static final int TASK_ERROR_INVALID_CONFIRM_USERNAME = 3511;
  public static final int TASK_ERROR_USER_ALREADY_EXISTS = 3512;
  public static final int TASK_ERROR_USER_NOT_FOUND_IN_SESSION = 3513;
  public static final int TASK_ERROR_INVALID_USERID = 3514;
  public static final int TASK_ERROR_UNABLE_TO_CREATE_CUSTOM_TAG_SERVICE = 3515;
  public static final int TASK_ERROR_UNABLE_TO_CREATE_USER_SERVICE = 3516;
  public static final int TASK_ERROR_UNABLE_TO_GET_USER_PROFILE_PROPERTIES_FILE = 3517;
  public static final int TASK_ERROR_CUSTOM_TAG_SERVICE_NOT_FOUND_IN_SESSION = 3518;
  public static final int TASK_ERROR_USERS_NOT_FOUND_IN_SESSION = 3519;
  public static final int TASK_ERROR_BUSINESS_EMPLOYEE_NOT_FOUND_IN_SESSION = 3520;
  public static final int TASK_ERROR_BUSINESS_EMPLOYEES_NOT_FOUND_IN_SESSION = 3521;
  public static final int TASK_ERROR_OLD_BUSINESS_EMPLOYEE_NOT_FOUND_IN_SESSION = 3522;
  public static final int TASK_ERROR_NO_ENTITLEMENT_GROUP_ID = 3523;
  public static final int TASK_ERROR_NO_USER_LIST_NAME = 3524;
  public static final int TASK_ERROR_NO_ADMIN_LIST_NAME = 3525;
  public static final int TASK_ERROR_UNABLE_TO_RETRIEVE_BAI_EXPORT_SETTINGS = 3526;
  public static final int TASK_ERROR_UNABLE_TO_STORE_BAI_EXPORT_SETTINGS = 3527;
  public static final int TASK_ERROR_MUST_SUPPLY_BUSINESS_FOR_BAI_EXPORT_SETTINGS = 3528;
  public static final int TASK_ERROR_NO_BUSINESS_IN_SESSION_UNDER_SPECIFIED_NAME = 3529;
  public static final int TASK_ERROR_BAI_EXPORT_SETTINGS_NO_CUSTOM_SENDER_IDENTIFICATION = 3530;
  public static final int TASK_ERROR_BAI_EXPORT_SETTINGS_NO_CUSTOM_RECEIVER_IDENTIFICATION = 3531;
  public static final int TASK_ERROR_BAI_EXPORT_SETTINGS_NO_CUSTOM_ULTIMATE_RECEIVER_IDENTIFICATION = 3532;
  public static final int TASK_ERROR_BAI_EXPORT_SETTINGS_NO_CUSTOM_ORIGINATOR_IDENTIFICATION = 3533;
  public static final int TASK_ERROR_NO_ADMIN_USER_DEFINED = 3534;
  public static final int TASK_ERROR_NO_BANK_ID = 3535;
  public static final int TASK_ERROR_INVALID_USER_TYPE = 3536;
  public static final int TASK_ERROR_NO_OPERATION_NAME = 3537;
  public static final int TASK_ERROR_CONTACT_POINT_NAME_TOO_LONG = 3538;
  public static final int TASK_ERROR_CONTACT_POINT_NAME_DNE = 3539;
  public static final int TASK_ERROR_CONTACT_POINT_DNE = 3540;
  public static final int TASK_ERROR_INVALID_CONTACT_POINT_ID = 3541;
  public static final int TASK_ERROR_CONTACT_POINTS_DNE = 3542;
  public static final int TASK_ERROR_CONTACT_POINT_EMAIL_ADDRESS_DNE = 3543;
  public static final int TASK_ERROR_CONTACT_POINT_NOT_DEFINED = 3544;
  public static final int TASK_ERROR_CONTACT_POINT_EMAIL_ADDRESS_INVALID = 3545;
  public static final int TASK_ERROR_CONTACT_POINT_ADDRESS_TOO_LONG = 3546;
  public static final int TASK_ERROR_CONTACT_POINT_TYPE_INVALID = 3547;
  public static final int TASK_ERROR_INVALID_BANK_USER = 3548;
  public static final int TASK_ERROR_INVALID_CONTACT_POIN_NAME = 3549;
  public static final int ERROR_ADD_USER_FIRST_TOO_LONG = 160;
  public static final int ERROR_ADD_USER_MIDDLE_TOO_LONG = 161;
  public static final int ERROR_ADD_USER_LAST_TOO_LONG = 162;
  public static final int ERROR_ADD_USER_STREET_TOO_LONG = 163;
  public static final int ERROR_ADD_USER_CITY_TOO_LONG = 164;
  public static final int ERROR_ADD_USER_ZIPCODE_TOO_LONG = 165;
  public static final int ERROR_ADD_USER_STATE_TOO_LONG = 166;
  public static final int ERROR_ADD_USER_COUNTRY_TOO_LONG = 167;
  public static final int ERROR_ADD_USER_CUSTID_TOO_LONG = 168;
  public static final int ERROR_ADD_USER_PHONE_TOO_LONG = 169;
  public static final int ERROR_ADD_USER_DATAPHONE_TOO_LONG = 170;
  public static final int ERROR_ADD_USER_EMAIL_TOO_LONG = 171;
  public static final int ERROR_ADD_USER_SSN_TOO_LONG = 172;
  public static final int ERROR_ADD_USER_TITLE_TOO_LONG = 173;
  public static final int ERROR_ADD_USER_GREETING_TOO_LONG = 174;
  public static final int ERROR_ADD_USER_USERNAME_TOO_LONG = 175;
  public static final int ERROR_ADD_USER_PASSWORD_TOO_LONG = 176;
  public static final int ERROR_ADD_USER_PASSWORD_CLUE_TOO_LONG = 177;
  public static final int ERROR_ADD_USER_PASSWORD_REMINDER_TOO_LONG = 178;
  public static final int ERROR_ADD_USER_BIRTHDATE_TOO_LONG = 179;
  public static final int ERROR_ADD_USER_FAXPHONE_TOO_LONG = 180;
  public static final int ERROR_ADD_USER_PREFERRED_LANGUAGE_TOO_LONG = 181;
  public static final int ERROR_ADD_USER_GREETING_TYPE_TOO_LONG = 182;
  public static final int ERROR_ADD_USER_FAMILY_TOO_LONG = 183;
  public static final int ERROR_ADD_USER_RESIDENCE_TOO_LONG = 184;
  public static final int ERROR_ADD_USER_INCOME_TOO_LONG = 185;
  public static final int ERROR_ADD_USER_INTENDED_USE_TOO_LONG = 186;
  public static final int ERROR_ADD_USER_GENDER_TOO_LONG = 187;
  public static final int ERROR_ADD_USER_AFFILIATE_BANK_ID_TOO_LONG = 188;
  public static final int ERROR_ADD_USER_PERSONAL_BANKER_TOO_LONG = 189;
  public static final int ERROR_ADD_USER_ACCOUNT_STATUS_TOO_LONG = 190;
  public static final int ERROR_ADD_USER_TIME_OUT_TOO_LONG = 191;
  public static final int ERROR_DISPLAY_SESSION_SUMMARY_TOO_LONG = 192;
  public static final int ERROR_USER_FIRST_TOO_LONG = 193;
  public static final int ERROR_USER_NAME_TOO_LONG = 194;
  public static final int ERROR_USER_LAST_TOO_LONG = 195;
}


/* Location:           D:\drops\jd\jars\efs.jar
 * Qualified Name:     com.ffusion.tasks.user.UserTask
 * JD-Core Version:    0.7.0.1
 */